version: "3.8"

networks:
  pri:

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    networks: 
     - pri
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
    volumes:
     - ./Containers/rabbitmq/etc/:/etc/rabbitmq/
     - ./Containers/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
     - ./Containers/rabbitmq/logs/:/var/log/rabbitmq/
     
  mongodb_container:
    build:
      context: ./Containers/mongodb
    container_name: mongodb
    image: mongo:latest
    restart: always
    networks:
      - pri
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./Containers/mongodb/data/db:/data/db
volumes:
  rabbitmq:
  mongodb:
