# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
registry: tomasforsman
network: filehandler_pri
name: filehandler
services:
- name: filehandler-api
  project: FileHandler/FileHandler.Api/FileHandler.Api.csproj
- name: filehandler-service
  project: FileHandler/FileHandler.Service/FileHandler.Service.csproj
  replicas: 1
- name: filewatcher-service
  project: FileWatcher/FileWatcher.Service/FileWatcher.Service.csproj
  env:
    - name: DOTNET_USE_POLLING_FILE_WATCHER
      value: 1
- name: filereader-service
  project: FileReader/FileReader.Service/FileReader.Service.csproj
  replicas: 1
- name: priwebcommunicator-service
  project: PriWebCommunicator/PriWebCommunicator.Service/PriWebCommunicator.Service.csproj
  replicas: 1
# - name: filesender-service
#   project: FileSender/FileSender.Service/FileSender.Service.csproj
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
- name: mongo
  image: mongo
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example
  bindings:
    - port: 27017
      connectionString: "mongodb://${host}:${port}"
- name: mongo-express
  image: mongo-express
  bindings:
    - port: 8081
      containerPort: 8081
      protocol: http
  env:
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example

